# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    clone: repo clone
    sr: search repos
    # token may not have privs. try
    # gh auth refresh -h github.com -s delete_repo
    repoDelete: 'api -X DELETE repos/$1'
    fork: repo fork --remote-name jade --remote
    my-prs: pr list -A @me
version: "1"
