third_party_dir = "third_party/rust"
manifest_path = "Cargo.toml"

# Parse Rust code to work out the precise set of source files for each crate.
precise_srcs = true
license_patterns = ["LICENSE*", "COPYING*", "UNLICENSE*"]

vendor = false

# Configuration for cargo (used both for vendoring and resolving dependencies)
[cargo]
# Support Cargo's unstable "artifact dependencies" functionality, RFC 3028.
bindeps = true

[buck]
rust_library = "cargo.rust_library"                            # A plain Rust library
rust_binary = "cargo.rust_binary"                              # A Rust executable
cxx_library = "cxx_library"                   # A C++ library (mostly for Rust -> C dependencies)
prebuilt_cxx_library = "prebuilt_cxx_library" # A prebuilt library (mostly for Rust -> C dependencies)
buildscript_genrule = "buildscript_run"                        # Rule for running a build script to produce rustc args and generated sources

# Load the macros to which the rules above will resolve.
buckfile_imports = """
load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")
load("@prelude//rust:cargo_package.bzl", "cargo")
"""

# Banner comment for the generated BUCK File.
generated_file_header = """
##
## \u0040generated by reindeer
## Do not edit by hand.
##
## Run reindeer buckify to update
"""
