package sandbox

import "errors"

// Sentinel errors for the sandbox package.
var (
	// Exec relay errors
	ErrRelayConnect    = errors.New("connect to exec relay")
	ErrRelaySend       = errors.New("send exec request")
	ErrRelayRead       = errors.New("read exec result")
	ErrRelayUnexpected = errors.New("unexpected message type")
	ErrRelayDecode     = errors.New("decode exec result")
	ErrRelayListen     = errors.New("listen on relay socket")
	ErrRelayProxy      = errors.New("relay port-forward proxy")

	// Rootfs errors
	ErrGuestAgent   = errors.New("guest-agent not found")
	ErrGuestFused   = errors.New("guest-fused not found")
	ErrGuestInit    = errors.New("guest-init not found")
	ErrResizeRootfs = errors.New("resize rootfs")
	ErrCreateRootfs = errors.New("create rootfs image")
	ErrCreateTemp   = errors.New("create temp file")
	ErrWriteTemp    = errors.New("write temp file")
	ErrDebugfs      = errors.New("debugfs")
	ErrStatRootfs   = errors.New("stat rootfs")
	ErrTruncate     = errors.New("truncate rootfs")
	ErrResize2fs    = errors.New("resize2fs")

	// Sandbox lifecycle errors (shared between darwin and linux)
	ErrRegisterState          = errors.New("register VM state")
	ErrAllocateSubnet         = errors.New("allocate subnet")
	ErrCreateCAPool           = errors.New("create CA pool")
	ErrCopyRootfs             = errors.New("copy rootfs")
	ErrPrepareRootfs          = errors.New("prepare rootfs")
	ErrPrepareBootstrapRoot   = errors.New("prepare bootstrap rootfs")
	ErrInjectCACert           = errors.New("inject CA cert into rootfs")
	ErrInvalidDiskCfg         = errors.New("invalid extra disk config")
	ErrCreateVM               = errors.New("create VM")
	ErrCreateProxy            = errors.New("create transparent proxy")
	ErrFirewallSetup          = errors.New("setup firewall rules")
	ErrNetworkStack           = errors.New("create network stack")
	ErrVFSListener            = errors.New("setup VFS listener")
	ErrVFSServer              = errors.New("start VFS server")
	ErrMachineClose           = errors.New("machine close")
	ErrPrepareOverlayMount    = errors.New("prepare overlay mount snapshot")
	ErrCopyOverlaySource      = errors.New("copy overlay mount source")
	ErrRemoveOverlaySnapshot  = errors.New("remove overlay mount snapshot")
	ErrOverlayLayerLimit      = errors.New("overlay layer limit exceeded")
	ErrOverlayDiskLimit       = errors.New("overlay disk device limit exceeded")
	ErrFirewallCleanup        = errors.New("firewall cleanup")
	ErrNATCleanup             = errors.New("NAT cleanup")
	ErrNetworkFile            = errors.New("get network file")
	ErrReleaseSubnet          = errors.New("release subnet")
	ErrUnregisterState        = errors.New("unregister VM state")
	ErrRemoveRootfs           = errors.New("remove rootfs copy")
	ErrProxyClose             = errors.New("proxy close")
	ErrLifecycleInit          = errors.New("initialize lifecycle record")
	ErrLifecycleUpdate        = errors.New("update lifecycle record")
	ErrPortForwardDial        = errors.New("dial guest port-forward service")
	ErrPortForwardInit        = errors.New("initialize guest port-forward")
	ErrPortForwardBind        = errors.New("bind local port-forward listener")
	ErrPortForwardCopy        = errors.New("proxy port-forward stream")
	ErrNoVsockDialer          = errors.New("vm backend does not support vsock dial")
	ErrVFSDisabled            = errors.New("vfs is disabled")
	ErrAllowListUnavailable   = errors.New("allow-list updates unavailable")
	ErrAllowListHosts         = errors.New("invalid allow-list hosts")
	ErrInteractiveUnsupported = errors.New("interactive exec unsupported")
	ErrInvalidMountConfig     = errors.New("invalid mount config")
)
