#!/bin/bash
bspc monitor -d I II III IV
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
aiopanel &
panelfix &
redshift &
which compton 2>&1 > /dev/null && compton &
