#!/usr/bin/env bash

resources="$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
simplify_paths=true
while true ; do
    case "$1" in
        --)
            shift
            break
            ;;
        --no-simplify-paths)
            simplify_paths=false
            shift
            ;;
        *)
            break
    esac
done

nix path-info -rsS --json "$@" \
    | jq -r -f "$resources/nix-path-info-graphviz.jq" \
        --argjson simplify_paths "$simplify_paths" \
    | dot -Tsvg

