export BROWSER="xdg-open"
export RUST_BACKTRACE=1

if [[ -z "$SSH_AUTH_SOCK" ]]; then
    export SSH_AUTH_SOCK=/tmp/$USER/ssh-agent.sock
fi

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
