export ZIM_HOME="$HOME/.local/share/zim"

# don't use git if avoidable
zstyle ':zim:zmodule' use 'degit'
zstyle ':zim' 'disable-version-check' 'true'
zstyle ':completion-sync:*:onchange' debug true
zstyle ':completion-sync:*' debug true

# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi

source ${ZIM_HOME}/init.zsh

# apple ssh agent is really persistent. it doesn't do fido2, which is no good.
# just don't use it at all tbh.
if [[ $SSH_AUTH_SOCK == /private/tmp/com.apple.launchd* ]]; then
    unset SSH_AUTH_SOCK
fi

# add the pwd to the history
# this is broken because it puts the crap in the up arrow menu. *sigh*
# function zshaddhistory() {
#     print -sr "${1%%$'\n'} ### ${PWD}"
#     fc -p
# }
if whence atuin >/dev/null 2>&1; then
    eval "$(ATUIN_NOBIND=true atuin init zsh)"
fi

if which direnv > /dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

# workaround a bug where /etc/zshrc is run on every shell startup including in shells descendent of other shells
# This is probably macOS shell behaviour bugs: the login shell is getting skipped due
# to terminal emulator configuration, so the Lix installer jams it in
# /etc/zshrc despite this getting executed recursively.
# Bug: https://git.lix.systems/lix-project/lix/issues/645
if [[ -v __ETC_PROFILE_NIX_SOURCED ]]; then
    export __ETC_PROFILE_NIX_SOURCED
fi

unsetopt extendedglob
# Disabled due to bad performance bug: https://github.com/BronzeDeer/zsh-completion-sync/issues/1
# source "${ZIM_HOME}/modules/zsh-completion-sync/zsh-completion-sync.plugin.zsh"
