# GHC's boot packages, read from each bindist's `lib/package.conf.d`.
#
# The data lives in `boot_packages.json`, generated by
# `buck run toolchains//:update_hermetic_toolchain -- haskell ...`; JSON so that
# hackage2buck can read the same table. Unit ids are hash-suffixed per platform,
# and paths are relative to the unpacked archive root.

load(":boot_packages.json", _BOOT = "value")

GHC_VERSION = _BOOT["ghc_version"]

GHC_PACKAGE_DB = _BOOT["package_db"]

BOOT_PACKAGES = _BOOT["packages"]
