#!/bin/bash

sock="$LC_SSH_CLIP_SOCK"
if [[ -z "$LC_SSH_CLIP_SOCK" ]]; then
    echo "LC_SSH_CLIP_SOCK unset, can't do anything" >&2
    exit 1
fi

# stdin/stdout are tty, paste to terminal
if [[ -t 0 && -t 1 ]]; then
    copy=0
    paste=1
else
    # stdin is not tty, so we might be getting piped into
    [[ ! -t 0 ]]
    paste=$?

    # stdout is not tty, so we might be getting piped out of
    [[ ! -t 1 ]]
    copy=$?
fi

while [[ $# -gt 0 ]]; do
    case $1 in
        -i)
            copy=1
            paste=0
            ;;
        -o)
            copy=0
            paste=1
            ;;
    esac
done


if [[ $copy == 1 ]]; then
    curl --silent --unix-socket "$sock" -XPOST -d '@-' http:/test
fi

if [[ $paste == 1 ]]; then
    curl --silent --unix-socket "$sock" http:/test
fi

