#!/usr/bin/env bash
bspc monitor -d I II III IV V VI VII VIII
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move

bspc rule -a '*:*:Plover\: Suggestions' sticky=true
bspc config external_rules_command ~/.config/bspwm/external_rules
AIOPANEL_LOG=aiopanel.PulseStateWatcher=debug aiopanel &
#panelfix &
poke-upower 5000 &
redshift &

# workaround nixos issue: services.x11.displayManager.* does this but we don't
# use that stuff.
dbus-update-activation-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY
systemctl --user import-environment DBUS_SESSION_BUS_ADDRESS XAUTHORITY DISPLAY XDG_SESSION_ID

which picom 2>&1 > /dev/null && picom --config /dev/null --backend glx --vsync &
