#!/usr/bin/env bash

wid=$1
class=$2
instance=$3

#echo $wid $class $instance >> ~/test.rules

if [[ "$class" = Hopper ]] ; then
		if xprop -id ${wid} _NET_WM_WINDOW_TYPE | grep -q _KDE_NET_WM_WINDOW_TYPE_OVERRIDE; then
				echo 'manage=off'
		fi
fi
